[package]
name = "rust-notifier"
version = "0.1.0"
authors = ["Fun Maker <funmaker95@gmail.com>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
websocket = "*"
rss = "0.4"
time = "0.1"
curl = "*"
lazy_static = "*"
regex = "*"
url = "1.2.1"
